package sdd.interiorexplorers.map;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.18 at 12:04:40 AM EDT 
//

import java.util.ArrayList;
import java.util.List;

import android.util.Log;

/**
 * <p>
 * Java class for Floor complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;Floor&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;node&quot; maxOccurs=&quot;unbounded&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;attribute name=&quot;Id&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *                 &lt;attribute name=&quot;Type&quot; use=&quot;required&quot; type=&quot;{}Types&quot; /&gt;
 *                 &lt;attribute name=&quot;Description&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *                 &lt;attribute name=&quot;X&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *                 &lt;attribute name=&quot;Y&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name=&quot;edge&quot; maxOccurs=&quot;unbounded&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;attribute name=&quot;FromId&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *                 &lt;attribute name=&quot;ToId&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name=&quot;elevator&quot; maxOccurs=&quot;unbounded&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;attribute name=&quot;Id&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *                 &lt;attribute name=&quot;ElevatorId&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *                 &lt;attribute name=&quot;X&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *                 &lt;attribute name=&quot;Y&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name=&quot;area&quot; maxOccurs=&quot;unbounded&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;attribute name=&quot;TopLeft&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *                 &lt;attribute name=&quot;TopRight&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *                 &lt;attribute name=&quot;BottomLeft&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *                 &lt;attribute name=&quot;BottomRight&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;Id&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

public class Floor {
	
	// protected members

	protected List<Floor.Node> node;

	protected List<Floor.Edge> edge;

	protected List<Floor.Elevator> elevator;

	protected List<Floor.Area> area;

	protected int id;

	/**
	 * Gets the value of the node property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the node property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getNode().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Floor.Node }
	 * 
	 * 
	 */
	public List<Floor.Node> getNode() {
		
		if (node == null) {
			node = new ArrayList<Floor.Node>();
		}
		return this.node;
	}

	/**
	 * Gets the value of the edge property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the edge property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getEdge().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Floor.Edge }
	 * 
	 * 
	 */
	public List<Floor.Edge> getEdge() {
		if (edge == null) {
			edge = new ArrayList<Floor.Edge>();
		}
		return this.edge;
	}

	/**
	 * Gets the value of the elevator property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the elevator property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getElevator().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Floor.Elevator }
	 * 
	 * 
	 */
	public List<Floor.Elevator> getElevator() {
		if (elevator == null) {
			elevator = new ArrayList<Floor.Elevator>();
		}
		return this.elevator;
	}

	/**
	 * Gets the value of the area property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the area property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getArea().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Floor.Area }
	 * 
	 * 
	 */
	public List<Floor.Area> getArea() {
		if (area == null) {
			area = new ArrayList<Floor.Area>();
		}
		return this.area;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public int getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(int value) {
		this.id = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;attribute name=&quot;TopLeft&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *       &lt;attribute name=&quot;TopRight&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *       &lt;attribute name=&quot;BottomLeft&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *       &lt;attribute name=&quot;BottomRight&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */

	public static class Area {

		protected int left;

		protected int right;

		protected int bottom;

		protected int top;

		protected int id;

		/**
		 * Gets the value of the topLeft property.
		 * 
		 */
		public int getLeft() {
			return left;
		}

		/**
		 * Sets the value of the topLeft property.
		 * 
		 */
		public void setLeft(int value) {
			this.left = value;
		}

		/**
		 * Gets the value of the topRight property.
		 * 
		 */
		public int getRight() {
			return right;
		}

		/**
		 * Sets the value of the topRight property.
		 * 
		 */
		public void setRight(int value) {
			this.right = value;
		}

		/**
		 * Sets the value of the Id property.
		 */
		public void setId(int value) {
			this.id = value;
		}

		/**
		 * Gets the value of the bottomLeft property.
		 * 
		 */
		public int getBottom() {
			return bottom;
		}

		/**
		 * Sets the value of the bottomLeft property.
		 * 
		 */
		public void setBottom(int value) {
			this.bottom = value;
		}

		/**
		 * Gets the value of the bottomRight property.
		 * 
		 */
		public int getTop() {
			return top;
		}

		/**
		 * Sets the value of the bottomRight property.
		 * 
		 */
		public void setTop(int value) {
			this.top = value;
		}

		/**
		 * Gets the value of the id property.
		 */
		public int getId() {
			return id;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;attribute name=&quot;FromId&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *       &lt;attribute name=&quot;ToId&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */

	public static class Edge {

		protected int fromId;

		protected int toId;

		/**
		 * Gets the value of the fromId property.
		 * 
		 */
		public int getFromId() {
			return fromId;
		}

		/**
		 * Sets the value of the fromId property.
		 * 
		 */
		public void setFromId(int value) {
			this.fromId = value;
		}

		/**
		 * Gets the value of the toId property.
		 * 
		 */
		public int getToId() {
			return toId;
		}

		/**
		 * Sets the value of the toId property.
		 * 
		 */
		public void setToId(int value) {
			this.toId = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;attribute name=&quot;Id&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *       &lt;attribute name=&quot;ElevatorId&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *       &lt;attribute name=&quot;X&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *       &lt;attribute name=&quot;Y&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */

	public static class Elevator {

		protected int id;

		protected int elevatorId;

		protected int x;

		protected int y;

		/**
		 * Gets the value of the id property.
		 * 
		 */
		public int getId() {
			return id;
		}

		/**
		 * Sets the value of the id property.
		 * 
		 */
		public void setId(int value) {
			this.id = value;
		}

		/**
		 * Gets the value of the elevatorId property.
		 * 
		 */
		public int getElevatorId() {
			return elevatorId;
		}

		/**
		 * Sets the value of the elevatorId property.
		 * 
		 */
		public void setElevatorId(int value) {
			this.elevatorId = value;
		}

		/**
		 * Gets the value of the x property.
		 * 
		 */
		public int getX() {
			return x;
		}

		/**
		 * Sets the value of the x property.
		 * 
		 */
		public void setX(int value) {
			this.x = value;
		}

		/**
		 * Gets the value of the y property.
		 * 
		 */
		public int getY() {
			return y;
		}

		/**
		 * Sets the value of the y property.
		 * 
		 */
		public void setY(int value) {
			this.y = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;attribute name=&quot;Id&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *       &lt;attribute name=&quot;Type&quot; use=&quot;required&quot; type=&quot;{}Types&quot; /&gt;
	 *       &lt;attribute name=&quot;Description&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
	 *       &lt;attribute name=&quot;X&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *       &lt;attribute name=&quot;Y&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */

	public static class Node {

		protected int id;

		protected Types type;

		protected String description;

		protected int x;

		protected int y;

		/**
		 * Gets the value of the id property.
		 * 
		 */
		public int getId() {
			return id;
		}

		/**
		 * Sets the value of the id property.
		 * 
		 */
		public void setId(int value) {
			this.id = value;
		}

		/**
		 * Gets the value of the type property.
		 * 
		 * @return possible object is {@link Types }
		 * 
		 */
		public Types getType() {
			return type;
		}

		/**
		 * Sets the value of the type property.
		 * 
		 * @param value
		 *            allowed object is {@link Types }
		 * 
		 */
		public void setType(Types value) {
			this.type = value;
		}

		/**
		 * Gets the value of the description property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDescription() {
			return description;
		}

		/**
		 * Sets the value of the description property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDescription(String value) {
			this.description = value;
		}

		/**
		 * Gets the value of the x property.
		 * 
		 */
		public int getX() {
			return x;
		}

		/**
		 * Sets the value of the x property.
		 * 
		 */
		public void setX(int value) {
			this.x = value;
		}

		/**
		 * Gets the value of the y property.
		 * 
		 */
		public int getY() {
			return y;
		}

		/**
		 * Sets the value of the y property.
		 * 
		 */
		public void setY(int value) {
			this.y = value;
		}

	}

}
