package sdd.interiorexplorers.map;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.18 at 12:04:40 AM EDT 
//

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */

public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: generated
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Floor }
	 * 
	 */
	public Floor createFloor() {
		return new Floor();
	}

	/**
	 * Create an instance of {@link Floor.Elevator }
	 * 
	 */
	public Floor.Elevator createFloorElevator() {
		return new Floor.Elevator();
	}

	/**
	 * Create an instance of {@link generated.Elevator }
	 * 
	 */
	public Elevator createElevator() {
		return new Elevator();
	}

	/**
	 * Create an instance of {@link Floor.Edge }
	 * 
	 */
	public Floor.Edge createFloorEdge() {
		return new Floor.Edge();
	}

	/**
	 * Create an instance of {@link Floor.Area }
	 * 
	 */
	public Floor.Area createFloorArea() {
		return new Floor.Area();
	}

	/**
	 * Create an instance of {@link Floor.Node }
	 * 
	 */
	public Floor.Node createFloorNode() {
		return new Floor.Node();
	}

	/**
	 * Create an instance of {@link Building }
	 * 
	 */
	public Building createBuilding() {
		return new Building();
	}

}
