package sdd.interiorexplorers.map;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.18 at 12:04:40 AM EDT 
//

/**
 * <p>
 * Java class for Types.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name=&quot;Types&quot;&gt;
 *   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;&gt;
 *     &lt;enumeration value=&quot;Bathroom&quot;/&gt;
 *     &lt;enumeration value=&quot;Elevator&quot;/&gt;
 *     &lt;enumeration value=&quot;Entrance&quot;/&gt;
 *     &lt;enumeration value=&quot;Exit&quot;/&gt;
 *     &lt;enumeration value=&quot;Room&quot;/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */

public enum Types {

	BATHROOM("Bathroom"),

	ELEVATOR("Elevator"),

	ENTRANCE("Entrance"),

	EXIT("Exit"),

	ROOM("Room"),
	
	HIDDEN("Hidden");
	private final String value;

	Types(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static Types fromValue(String v) {
		for (Types c : Types.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
